<script lang="ts">
  import { ArrowLeft, ArrowRight, MoveRight } from 'lucide-svelte';
  import type { Project } from '$lib/types';
  import MechanicalButton from './MechanicalButton.svelte';
  import ProjectStatus from './ProjectStatus.svelte';
  import ProjectVisual from './ProjectVisual.svelte';
  import TechTag from './TechTag.svelte';

  let { project, nextProject }: { project: Project; nextProject: Project } = $props();
  const copy = $derived(project.caseStudy);
  const chapters = $derived([
    ['Overview', 'overview'], ['Context', 'context'], ['Problem', 'problem'], ['UX Thinking', 'ux-thinking'], ['User Flow', 'user-flow'],
    ['Wireframes', 'wireframes'], ['Visual Design', 'visual-design'], ['Interaction Design', 'interaction-design'], ['Development', 'development'],
    ...(copy.technicalArchitecture ? [['Technical Architecture', 'technical-architecture']] : []), ['Challenges', 'challenges'], ['Result', 'result'], ['What I Learned', 'what-i-learned'], ['Future Improvements', 'future-improvements']
  ]);
</script>

<article class="case-study" style={`--project-accent: ${project.accent}`}>
  <header class="case-hero content-shell"><a class="back-link" href="/work"><ArrowLeft size={16} strokeWidth={1.6} aria-hidden="true" />WORK INDEX</a><div class="case-hero__title"><div><p class="eyebrow">CASE STUDY / {project.number}</p><h1 class="chrome-text">{project.name}</h1></div><ProjectStatus status={project.status} /></div><div class="case-hero__meta"><div><span>ROLE</span><strong>{project.role}</strong></div><div><span>CATEGORY</span><strong>{project.category}</strong></div><div><span>YEAR</span><strong>{project.year}</strong></div></div></header>
  <div class="case-visual content-shell"><ProjectVisual {project} /></div>
  <div class="case-chassis chrome-rail"><div class="content-shell case-chassis__inner"><span>{project.number} / {project.name}</span><span>UX / UI / DEVELOPMENT</span><span>SCROLL TO INSPECT</span></div></div>

  <div class="case-layout content-shell">
    <aside class="case-index"><p>CASE INDEX</p><nav aria-label="Case study chapters">{#each chapters as chapter, index}<a href={`#${chapter[1]}`}><span>{String(index + 1).padStart(2, '0')}</span>{chapter[0]}</a>{/each}</nav></aside>
    <div class="case-content">
      <section id="overview" class="case-section"><div class="section-label"><span>01</span><p>Overview</p></div><div class="section-copy"><h2>Overview</h2><p class="lead-copy">{copy.overview}</p></div></section>
      <section id="context" class="case-section"><div class="section-label"><span>02</span><p>Context</p></div><div class="section-copy"><h2>Context</h2><p>{copy.context}</p></div></section>
      <section id="problem" class="case-section"><div class="section-label"><span>03</span><p>Define</p></div><div class="section-copy"><h2>Problem</h2><p>{copy.problem}</p><div class="problem-frame metal-panel"><span>PROBLEM STATEMENT / 001</span><strong>How might the interface make a complex system feel direct, legible, and satisfying to use?</strong><i aria-hidden="true"></i></div></div></section>
      <section id="ux-thinking" class="case-section"><div class="section-label"><span>04</span><p>Understand</p></div><div class="section-copy"><h2>UX Thinking</h2><p>{copy.uxThinking}</p></div></section>
      <section id="user-flow" class="case-section"><div class="section-label"><span>05</span><p>Flow</p></div><div class="section-copy"><h2>User Flow</h2><p>{copy.userFlow}</p><div class="ux-flow" aria-label="User flow diagram">{#each ['ENTRY', 'ORIENT', 'SELECT', 'ACTION', 'RESULT'] as step, index}<div><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong></div>{#if index < 4}<MoveRight size={20} strokeWidth={1.2} aria-hidden="true" />{/if}{/each}</div></div></section>
      <section id="wireframes" class="case-section case-section--wide"><div class="section-label"><span>06</span><p>Structure</p></div><div class="section-copy"><h2>Wireframes</h2><p>{copy.wireframes}</p><div class="wireframe-grid"><div class="wireframe-sheet" role="img" aria-label="Desktop wireframe placeholder"><div class="wf-toolbar"></div><div class="wf-sidebar"></div><div class="wf-main"><i></i><i></i><span></span><span></span><span></span></div><b>DESKTOP / FLOW 01</b></div><div class="wireframe-sheet wireframe-sheet--mobile" role="img" aria-label="Mobile wireframe placeholder"><div class="wf-toolbar"></div><div class="wf-main"><i></i><span></span><span></span><span></span></div><b>MOBILE / FLOW 02</b></div></div></div></section>
      <section id="visual-design" class="case-section case-section--wide"><div class="section-label"><span>07</span><p>System</p></div><div class="section-copy"><h2>Visual Design</h2><p>{copy.visualDesign}</p><ProjectVisual {project} compact /><div class="design-tokens"><div><span>PRIMARY</span><i style={`background:${project.accent}`}></i><b>{project.accent}</b></div><div><span>SURFACE</span><i style="background:#0b0e16"></i><b>#0B0E16</b></div><div><span>TYPE</span><i style="background:#eef1f6"></i><b>#EEF1F6</b></div></div></div></section>
      <section id="interaction-design" class="case-section"><div class="section-label"><span>08</span><p>Motion</p></div><div class="section-copy"><h2>Interaction Design</h2><p>{copy.interactionDesign}</p><div class="interaction-track" aria-label="Interaction sequence">{#each ['REST', 'FOCUS', 'SELECT'] as state, index}<div class:active={index === 2}><span>{state}</span><i><b></b></i><small>0{index + 1} / 120MS</small></div>{/each}</div></div></section>
      <section id="development" class="case-section"><div class="section-label"><span>09</span><p>Build</p></div><div class="section-copy"><h2>Development</h2><p>{copy.development}</p><div class="development-console"><div><span>01</span><code>component.interface()</code><b>READY</b></div><div><span>02</span><code>responsive.layout()</code><b>READY</b></div><div><span>03</span><code>data.connect()</code><b>STAGED</b></div></div></div></section>
      {#if copy.technicalArchitecture}<section id="technical-architecture" class="case-section"><div class="section-label"><span>10</span><p>Systems</p></div><div class="section-copy"><h2>Technical Architecture</h2><p>{copy.technicalArchitecture}</p></div></section>{/if}
      <section id="challenges" class="case-section"><div class="section-label"><span>{copy.technicalArchitecture ? '11' : '10'}</span><p>Learn</p></div><div class="section-copy"><h2>Challenges</h2><p>{copy.challenges}</p></div></section>
      <section id="result" class="case-section"><div class="section-label"><span>{copy.technicalArchitecture ? '12' : '11'}</span><p>Output</p></div><div class="section-copy"><h2>Result</h2><p class="lead-copy">{copy.result}</p><div class="result-mark"><span>END OF CASE</span><strong>{project.number}</strong></div></div></section>
      <section id="what-i-learned" class="case-section"><div class="section-label"><span>{copy.technicalArchitecture ? '13' : '12'}</span><p>Reflect</p></div><div class="section-copy"><h2>What I Learned</h2><p>{copy.whatILearned}</p></div></section>
      <section id="future-improvements" class="case-section"><div class="section-label"><span>{copy.technicalArchitecture ? '14' : '13'}</span><p>Next</p></div><div class="section-copy"><h2>Future Improvements</h2><p>{copy.futureImprovements}</p></div></section>
      <section id="links" class="case-links"><div><p class="eyebrow">Technologies</p><h2>Build rack</h2><div class="technology-list">{#each project.technologies as technology}<TechTag label={technology} />{/each}</div></div><div><p class="eyebrow">Links</p><h2>Open channel</h2><div class="link-list"><MechanicalButton href={project.live_url} label="Open website" external /><MechanicalButton href={project.github_url || undefined} label="Repository" variant="dark" disabled={!project.github_url} /><MechanicalButton href={project.prototype_url || undefined} label="Prototype" variant="ghost" disabled={!project.prototype_url} /></div></div></section>
    </div>
  </div>
  <a class="next-project" href={`/work/${nextProject.slug}`} style={`--next-accent: ${nextProject.accent}`}><div class="content-shell next-project__inner"><div><span>NEXT CASE / {nextProject.number}</span><h2>{nextProject.name}</h2></div><ArrowRight size={42} strokeWidth={1.2} aria-hidden="true" /></div></a>
</article>

<style>
  .case-hero { padding: clamp(54px, 8vw, 115px) 0 clamp(42px, 6vw, 78px); } .back-link { display: inline-flex; align-items: center; gap: 9px; margin-bottom: clamp(48px, 7vw, 90px); color: var(--muted); font: 700 0.59rem/1 var(--mono); letter-spacing: 0.08em; text-decoration: none; } .back-link:hover { color: var(--cyan); } .case-hero__title { display: flex; align-items: end; justify-content: space-between; gap: 30px; } .case-hero h1 { margin: 20px 0 0; font: 700 clamp(5.3rem, 12vw, 13rem)/0.68 var(--display); letter-spacing: -0.07em; text-transform: uppercase; } .case-hero__meta { display: grid; grid-template-columns: 1.2fr 1fr 0.4fr; gap: 8px; margin-top: clamp(42px, 6vw, 72px); } .case-hero__meta div { display: flex; min-height: 65px; flex-direction: column; gap: 9px; padding: 14px; border: 1px solid rgba(185, 198, 216, 0.23); background: linear-gradient(180deg, #1b212c, #0b0e15); box-shadow: inset 0 1px rgba(255, 255, 255, 0.08); } .case-hero__meta span { color: var(--muted-dark); font: 700 0.52rem/1 var(--mono); letter-spacing: 0.08em; } .case-hero__meta strong { color: var(--silver); font: 600 0.87rem/1.3 var(--display); letter-spacing: 0.03em; text-transform: uppercase; } .case-visual { padding-bottom: clamp(60px, 9vw, 120px); } .case-chassis__inner { display: grid; grid-template-columns: 1fr auto 1fr; min-height: 34px; align-items: center; gap: 20px; font: 700 0.56rem/1 var(--mono); letter-spacing: 0.08em; } .case-chassis__inner span:nth-child(2) { text-align: center; } .case-chassis__inner span:last-child { text-align: right; }
  .case-layout { display: grid; grid-template-columns: 190px minmax(0, 1fr); gap: clamp(40px, 8vw, 125px); padding-block: clamp(85px, 12vw, 170px); } .case-index { position: sticky; top: 130px; height: max-content; } .case-index > p { margin: 0 0 15px; color: var(--muted-dark); font: 700 0.56rem/1 var(--mono); letter-spacing: 0.08em; } .case-index nav { display: flex; flex-direction: column; border-top: 1px solid rgba(187, 199, 216, 0.23); } .case-index a { display: flex; min-height: 36px; align-items: center; gap: 11px; border-bottom: 1px solid rgba(187, 199, 216, 0.12); color: var(--muted); font: 700 0.52rem/1 var(--mono); text-decoration: none; text-transform: uppercase; } .case-index a:hover { color: var(--project-accent); } .case-index a span { color: var(--muted-dark); } .case-content { min-width: 0; } .case-section { display: grid; grid-template-columns: 115px minmax(0, 760px); justify-content: space-between; gap: 30px; padding: 0 0 clamp(90px, 12vw, 160px); scroll-margin-top: 135px; } .case-section--wide { grid-template-columns: 115px minmax(0, 980px); } .section-label { padding-top: 10px; } .section-label span { display: block; margin-bottom: 9px; color: var(--project-accent); font: 700 0.66rem/1 var(--mono); } .section-label p { margin: 0; color: var(--muted-dark); font: 700 0.54rem/1 var(--mono); letter-spacing: 0.07em; text-transform: uppercase; } .section-copy h2 { margin: 0 0 28px; font: 700 clamp(3.5rem, 6vw, 6.6rem)/0.77 var(--display); letter-spacing: -0.05em; text-transform: uppercase; } .section-copy > p { max-width: 66ch; color: var(--muted); font-size: 1.02rem; line-height: 1.72; } .section-copy .lead-copy { color: var(--silver); font: 500 clamp(1.35rem, 2.2vw, 2rem)/1.42 var(--display); }
  .problem-frame { display: grid; gap: 22px; margin-top: 42px; padding: clamp(25px, 4vw, 44px); } .problem-frame > * { position: relative; z-index: 1; } .problem-frame span { color: var(--project-accent); font: 700 0.57rem/1 var(--mono); letter-spacing: 0.08em; } .problem-frame strong { max-width: 24ch; color: var(--paper); font: 600 clamp(1.6rem, 3vw, 2.8rem)/1.05 var(--display); text-transform: uppercase; } .problem-frame i { width: 100%; height: 3px; background: linear-gradient(90deg, var(--project-accent), transparent); } .ux-flow { display: grid; grid-template-columns: 1fr auto 1fr auto 1fr auto 1fr auto 1fr; align-items: center; gap: 10px; margin-top: 42px; padding: 25px 20px; border-block: 1px solid rgba(188, 200, 218, 0.23); } .ux-flow div { display: flex; min-height: 84px; align-items: center; justify-content: center; flex-direction: column; gap: 10px; border: 1px solid rgba(189, 201, 219, 0.25); background: linear-gradient(145deg, #202734, #0a0d14); } .ux-flow div span { color: var(--project-accent); font: 700 0.52rem/1 var(--mono); } .ux-flow div strong { color: var(--silver); font: 700 0.59rem/1 var(--mono); } .ux-flow > :global(svg) { color: var(--muted-dark); }
  .wireframe-grid { display: grid; grid-template-columns: 1.4fr 0.7fr; gap: 12px; margin-top: 42px; } .wireframe-sheet { position: relative; display: grid; min-height: 390px; grid-template-columns: 22% 1fr; grid-template-rows: 36px 1fr; gap: 10px; padding: 20px 20px 46px; border: 1px solid #8394ad; color: #6481a4; background-color: #d9e4ee; background-image: linear-gradient(rgba(75, 110, 151, 0.14) 1px, transparent 1px), linear-gradient(90deg, rgba(75, 110, 151, 0.14) 1px, transparent 1px); background-size: 18px 18px; box-shadow: 8px 8px 0 rgba(66, 81, 101, 0.23); } .wireframe-sheet--mobile { grid-template-columns: 1fr; width: 75%; justify-self: center; } .wf-toolbar { grid-column: 1 / -1; border: 2px solid #6b829e; } .wf-sidebar { border: 2px solid #6b829e; } .wf-main { display: flex; flex-direction: column; gap: 14px; padding: 14px; border: 2px solid #6b829e; } .wf-main i { width: 55%; height: 26px; border: 2px solid #6b829e; } .wf-main span { height: 12%; min-height: 28px; border: 2px solid #6b829e; } .wireframe-sheet > b { position: absolute; bottom: 14px; left: 20px; font: 700 0.55rem/1 var(--mono); letter-spacing: 0.08em; }
  .design-tokens { display: grid; grid-template-columns: repeat(3, 1fr); gap: 7px; margin-top: 12px; } .design-tokens div { display: grid; grid-template-columns: auto 24px; align-items: center; gap: 8px; padding: 11px; border: 1px solid rgba(188, 200, 218, 0.2); background: #0a0e16; } .design-tokens span { color: var(--muted); font: 700 0.51rem/1 var(--mono); } .design-tokens i { width: 24px; height: 24px; grid-row: 1 / span 2; grid-column: 2; border: 1px solid rgba(255, 255, 255, 0.25); } .design-tokens b { color: var(--silver); font: 400 0.58rem/1 var(--mono); } .interaction-track { display: grid; grid-template-columns: repeat(3, 1fr); gap: 7px; margin-top: 42px; } .interaction-track > div { display: flex; min-height: 170px; align-items: center; flex-direction: column; justify-content: space-between; padding: 16px; border: 1px solid rgba(188, 200, 218, 0.23); background: linear-gradient(145deg, #1b222d, #090c13); } .interaction-track span, .interaction-track small { align-self: flex-start; color: var(--muted); font: 700 0.52rem/1 var(--mono); letter-spacing: 0.07em; } .interaction-track i { position: relative; display: block; width: 62%; height: 34px; border: 1px solid #768192; background: linear-gradient(180deg, #d8dce3, #67717f 52%, #b6bdc7); box-shadow: 0 3px 0 #03040a; } .interaction-track i b { position: absolute; top: 50%; left: 14%; width: 38%; height: 3px; transform: translateY(-50%); background: #171b22; } .interaction-track .active i { transform: translateY(2px); box-shadow: inset 0 2px 6px rgba(0, 0, 0, 0.6); } .interaction-track .active i b { background: var(--project-accent); }
  .development-console { margin-top: 42px; border: 1px solid rgba(188, 200, 218, 0.23); background: #05070b; box-shadow: inset 0 4px 14px black; } .development-console div { display: grid; grid-template-columns: 35px 1fr auto; min-height: 48px; align-items: center; gap: 15px; padding: 0 15px; border-bottom: 1px solid rgba(188, 200, 218, 0.1); } .development-console span { color: var(--muted); font: 400 0.52rem/1 var(--mono); } .development-console code { color: #aeb8c6; font: 400 0.72rem/1 var(--mono); } .development-console b { color: var(--cyan); font: 700 0.52rem/1 var(--mono); } .development-console div:last-child b { color: var(--amber); } .result-mark { display: flex; align-items: end; justify-content: space-between; margin-top: 40px; padding-top: 18px; border-top: 1px solid rgba(188, 200, 218, 0.24); } .result-mark span { color: var(--muted); font: 700 0.56rem/1 var(--mono); letter-spacing: 0.08em; } .result-mark strong { color: var(--project-accent); font: 700 clamp(4rem, 8vw, 8rem)/0.7 var(--display); }
  .case-links { display: grid; grid-template-columns: 1fr 1fr; gap: clamp(35px, 7vw, 90px); padding: clamp(35px, 6vw, 65px); border-block: 1px solid rgba(188, 200, 218, 0.24); background: linear-gradient(115deg, rgba(86, 111, 229, 0.09), rgba(150, 104, 223, 0.05)); scroll-margin-top: 130px; } .case-links h2 { margin: 15px 0 25px; font: 700 clamp(2.7rem, 4vw, 4.3rem)/0.8 var(--display); text-transform: uppercase; } .technology-list, .link-list { display: flex; flex-wrap: wrap; gap: 8px; } .next-project { display: block; color: var(--paper); border-top: 1px solid rgba(188, 200, 218, 0.23); background: linear-gradient(90deg, color-mix(in srgb, var(--next-accent) 13%, #080b12), #080b12 65%); text-decoration: none; } .next-project__inner { display: flex; min-height: 260px; align-items: center; justify-content: space-between; gap: 30px; } .next-project span { color: var(--next-accent); font: 700 0.59rem/1 var(--mono); letter-spacing: 0.08em; } .next-project h2 { margin: 16px 0 0; font: 700 clamp(4rem, 8vw, 8.4rem)/0.72 var(--display); letter-spacing: -0.055em; text-transform: uppercase; } .next-project :global(svg) { transition: transform 180ms ease; } .next-project:hover :global(svg) { transform: translateX(7px); }
  @media (max-width: 900px) { .case-layout { grid-template-columns: 1fr; } .case-index { position: static; overflow-x: auto; } .case-index nav { flex-direction: row; } .case-index a { min-width: max-content; padding-right: 22px; } .case-section, .case-section--wide { grid-template-columns: 80px minmax(0, 1fr); } } @media (max-width: 660px) { .case-hero__title { align-items: flex-start; flex-direction: column; } .case-hero h1 { font-size: clamp(4.5rem, 21vw, 7.5rem); } .case-hero__meta { grid-template-columns: 1fr; } .case-chassis__inner { grid-template-columns: 1fr auto; } .case-chassis__inner span:nth-child(2) { display: none; } .case-section, .case-section--wide { grid-template-columns: 1fr; gap: 15px; } .wireframe-grid { grid-template-columns: 1fr; } .wireframe-sheet { min-height: 300px; } .wireframe-sheet--mobile { width: 100%; } .ux-flow { grid-template-columns: 1fr; } .ux-flow > :global(svg) { transform: rotate(90deg); justify-self: center; } .design-tokens, .interaction-track { grid-template-columns: 1fr; } .case-links { grid-template-columns: 1fr; padding-inline: 20px; } .next-project__inner { min-height: 220px; } .next-project h2 { font-size: clamp(3.6rem, 17vw, 5.4rem); } } @media (max-width: 420px) { .case-hero h1 { font-size: clamp(2.9rem, 15.5vw, 4rem); overflow-wrap: anywhere; } }
</style>
