<script lang="ts">
  import { page } from '$app/state';
  import { Menu, X } from 'lucide-svelte';

  let menuOpen = $state(false);
  const links = [
    { label: 'Work', href: '/work', index: '01' },
    { label: 'About', href: '/about', index: '02' },
    { label: 'Web', href: '/web', index: '03' },
    { label: 'Lab', href: '/lab', index: '04' },
    { label: 'Contact', href: '/contact', index: '05' }
  ];
  function isActive(href: string) { return page.url.pathname === href || page.url.pathname.startsWith(`${href}/`); }
</script>

<header class="site-header">
  <div class="identity-strip"><div class="identity-strip__inner content-shell"><a class="brand-lockup" href="/" onclick={() => (menuOpen = false)}><span class="brand-lockup__badge">ZA</span><span>ZAIN AHMED</span></a><p class="role-lockup">UI/UX DESIGNER <span>/</span> WEB DEVELOPER</p><div class="system-readout" aria-label="Portfolio system online"><span class="system-readout__light" aria-hidden="true"></span><span>PORTFOLIO / 2026</span></div><button class="menu-toggle" type="button" aria-label={menuOpen ? 'Close navigation menu' : 'Index, open navigation menu'} aria-expanded={menuOpen} aria-controls="primary-navigation" onclick={() => (menuOpen = !menuOpen)}><span>{menuOpen ? 'CLOSE' : 'INDEX'}</span>{#if menuOpen}<X size={18} aria-hidden="true" />{:else}<Menu size={18} aria-hidden="true" />{/if}</button></div></div>
  <div class="nav-chassis chrome-rail"><nav id="primary-navigation" class:nav-open={menuOpen} class="primary-nav content-shell" aria-label="Primary navigation">{#each links as link}<a href={link.href} class:active={isActive(link.href)} aria-current={isActive(link.href) ? 'page' : undefined} onclick={() => (menuOpen = false)}><span class="nav-index">{link.index}</span><span>{link.label}</span><span class="nav-indicator" aria-hidden="true"></span></a>{/each}</nav></div>
</header>

<style>
  .site-header { position: sticky; z-index: 100; top: 0; filter: drop-shadow(0 10px 18px rgba(0, 0, 0, 0.32)); } .identity-strip { color: var(--paper); border-bottom: 1px solid rgba(213, 219, 230, 0.2); background: linear-gradient(90deg, rgba(83, 103, 255, 0.1), transparent 28%, transparent 74%, rgba(123, 88, 213, 0.1)), rgba(6, 8, 14, 0.93); backdrop-filter: blur(14px); } .identity-strip__inner { display: grid; grid-template-columns: 1fr auto 1fr; min-height: 46px; align-items: center; gap: 22px; } .brand-lockup { display: flex; align-items: center; gap: 10px; width: max-content; font: 700 0.82rem/1 var(--display); letter-spacing: 0.1em; text-decoration: none; } .brand-lockup__badge { display: grid; width: 25px; height: 25px; place-items: center; border: 1px solid rgba(236, 240, 246, 0.65); color: var(--chrome); background: linear-gradient(145deg, #374050, #0c0f17); box-shadow: inset 0 1px rgba(255, 255, 255, 0.2); font: 700 0.57rem/1 var(--mono); } .role-lockup { margin: 0; color: var(--silver); font: 600 0.72rem/1 var(--display); letter-spacing: 0.13em; } .role-lockup span { padding-inline: 5px; color: var(--violet); } .system-readout { display: flex; align-items: center; justify-content: flex-end; gap: 8px; color: var(--muted); font: 400 0.59rem/1 var(--mono); letter-spacing: 0.1em; } .system-readout__light { width: 6px; height: 6px; background: var(--cyan); box-shadow: 0 0 7px rgba(99, 216, 255, 0.65); } .nav-chassis { min-height: 52px; } .primary-nav { display: grid; grid-template-columns: repeat(5, 1fr); gap: 2px; padding-block: 6px; } .primary-nav a { position: relative; display: flex; min-height: 38px; align-items: center; justify-content: center; gap: 12px; overflow: hidden; border: 1px solid rgba(15, 18, 25, 0.82); border-radius: 3px; color: #11151d; background: linear-gradient(180deg, rgba(248, 249, 251, 0.72), rgba(112, 121, 134, 0.2)); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.8), inset 0 -2px 2px rgba(17, 20, 27, 0.42); font: 700 0.76rem/1 var(--mono); letter-spacing: 0.08em; text-decoration: none; text-transform: uppercase; transition: color 160ms ease, background 160ms ease, transform 120ms ease; } .primary-nav a:hover, .primary-nav a.active { color: var(--paper); background: linear-gradient(180deg, #2f3745, #0b0f17 55%, #222a36); box-shadow: inset 0 2px 8px rgba(0, 0, 0, 0.75), inset 0 1px 0 rgba(255, 255, 255, 0.12); } .primary-nav a:active { transform: translateY(1px); } .nav-index { opacity: 0.55; font-size: 0.53rem; } .nav-indicator { position: absolute; right: 9px; bottom: 5px; left: 9px; height: 2px; transform: scaleX(0); background: linear-gradient(90deg, var(--cobalt), var(--cyan)); box-shadow: 0 0 7px rgba(99, 216, 255, 0.75); transition: transform 160ms ease; } .primary-nav a:hover .nav-indicator, .primary-nav a.active .nav-indicator { transform: scaleX(1); } .menu-toggle { display: none; }
  @media (max-width: 760px) { .identity-strip__inner { grid-template-columns: 1fr auto; min-height: 56px; } .role-lockup, .system-readout { display: none; } .menu-toggle { display: inline-flex; min-height: 42px; align-items: center; gap: 10px; padding: 0 13px; border: 1px solid rgba(208, 216, 228, 0.42); border-radius: 2px; color: var(--paper); background: linear-gradient(180deg, #28303d, #0c1018); box-shadow: inset 0 1px rgba(255, 255, 255, 0.12); font: 700 0.62rem/1 var(--mono); letter-spacing: 0.08em; } .nav-chassis { min-height: 9px; } .primary-nav { display: none; grid-template-columns: 1fr; gap: 3px; padding-block: 8px 10px; } .primary-nav.nav-open { display: grid; } .primary-nav a { min-height: 48px; justify-content: flex-start; padding-inline: 16px; } }
</style>
